sandbox:
  judge:
    pool-sizes:
      java: 1
      python: 100
      cpp: 1
    concurrences:
      java: 1
      python: 1
      cpp: 1
  rabbitmq:
    enabled: false
    result-type: mq # mq/redis
  docker:
    cpu-limit: 1     # CPU 限制，单位核数
    memory-limit: 64 # 内存限制，单位 MB
    pid-limit: 32    # 进程数限制
    images:
      java: eclipse-temurin:8-jdk-alpine
      python: python:3.11-alpine
      cpp: frolvlad/alpine-gxx